#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
generate_facemocap_report_pngs.py

Generate three simple PNG figures for the FaceMoCap technical report:

  1) reference_comparison_auc_placeholder.png
  2) aev3_followup_global_metrics_placeholder.png
  3) aev3_followup_region_side_placeholder.png

The script intentionally creates conservative, report-oriented figures from the
CSV outputs already generated by the evaluation scripts. It does not require
seaborn and writes PNG files only.

Recommended usage:

python generate_facemocap_report_pngs.py \
  --reference_csv align_mean_movement_refactor/healthy_reference_eval_summary/reference_metric_comparison_global.csv \
  --followup_change_csv align_mean_movement_refactor/aev3_followup_eval_matched/followup_change_from_baseline.csv \
  --followup_region_side_csv align_mean_movement_refactor/aev3_followup_eval_matched/followup_region_side_metrics.csv \
  --common_movements_csv align_mean_movement_refactor/aev3_followup_eval_matched/followup_common_movements_by_participant.csv \
  --out_dir figures
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Set, Tuple

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


REFERENCE_LABELS = {
    "aev3": "AE",
    "mean_velocity": "Mean velocity",
    "mean_trajectory": "Mean trajectory",
}

METRIC_LABELS = {
    "trajectory_mae": "Trajectory\nMAE",
    "aligned_mae": "Aligned\nMAE",
    "displacement_mae": "Displacement\nMAE",
    "amplitude_log_ratio_abs": "Amplitude\nabnormality",
    "hyperkinesia_proxy": "Hyperkinesia\nproxy",
    "hypokinesia_proxy": "Hypokinesia\nproxy",
    "counter_direction_ratio": "Counter-direction\nratio",
}

GLOBAL_FOLLOWUP_METRICS = [
    "trajectory_mae",
    "amplitude_log_ratio_abs",
    "hyperkinesia_proxy",
    "counter_direction_ratio",
]

REFERENCE_COMPARISON_METRICS = [
    "trajectory_mae",
    "amplitude_log_ratio_abs",
    "hyperkinesia_proxy",
    "hypokinesia_proxy",
    "counter_direction_ratio",
]


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def save_fig(fig: plt.Figure, out_path: Path, dpi: int) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.tight_layout()
    fig.savefig(out_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)
    print(f"[OK] Wrote {out_path}")


def numeric(series: pd.Series) -> pd.Series:
    return pd.to_numeric(series, errors="coerce")


def label_metric(metric: str) -> str:
    return METRIC_LABELS.get(metric, metric.replace("_", " "))


def label_reference(reference: str) -> str:
    return REFERENCE_LABELS.get(reference, reference.replace("_", " "))


def plot_reference_comparison_auc(reference_csv: Path, out_path: Path, dpi: int) -> None:
    df = pd.read_csv(reference_csv)
    required = {"level", "movement", "reference", "metric", "auc_pathological_greater"}
    missing = required.difference(df.columns)
    if missing:
        raise ValueError(f"Missing columns in {reference_csv}: {sorted(missing)}")

    d = df.copy()
    d = d[(d["level"].astype(str) == "global") & (d["movement"].astype(str) == "ALL")]
    d = d[d["metric"].isin(REFERENCE_COMPARISON_METRICS)].copy()
    d["auc_pathological_greater"] = numeric(d["auc_pathological_greater"])
    d["metric_label"] = d["metric"].map(label_metric)
    d["reference_label"] = d["reference"].map(label_reference)

    metric_order = [label_metric(m) for m in REFERENCE_COMPARISON_METRICS if m in set(d["metric"])]
    reference_order = [label_reference(r) for r in ["aev3", "mean_velocity", "mean_trajectory"] if r in set(d["reference"])]
    pivot = d.pivot_table(
        index="metric_label",
        columns="reference_label",
        values="auc_pathological_greater",
        aggfunc="mean",
    )
    pivot = pivot.reindex(metric_order)
    pivot = pivot[[c for c in reference_order if c in pivot.columns]]

    fig, ax = plt.subplots(figsize=(11.5, 6.0))
    pivot.plot(kind="bar", ax=ax, width=0.82)
    ax.set_title("Healthy-reference comparison by pathology contrast")
    ax.set_ylabel("AUC: pathological > healthy evaluation")
    ax.set_xlabel("")
    ax.set_ylim(0.45, 1.02)
    ax.axhline(0.5, linewidth=1, linestyle="--")
    ax.legend(title="Reference", loc="lower right")
    ax.tick_params(axis="x", rotation=0)

    for container in ax.containers:
        ax.bar_label(container, fmt="%.2f", fontsize=8, padding=2)

    save_fig(fig, out_path, dpi)


def _last_visit_rows(change_df: pd.DataFrame) -> pd.DataFrame:
    d = change_df.copy()
    d["days_from_baseline"] = numeric(d["days_from_baseline"])
    d = d.dropna(subset=["participant_id", "days_from_baseline"])
    idx = d.groupby("participant_id")["days_from_baseline"].idxmax()
    out = d.loc[idx].copy()
    out = out[out["days_from_baseline"] > 0].copy()
    return out.sort_values("participant_id")


def plot_followup_global_metrics(change_csv: Path, out_path: Path, dpi: int) -> None:
    df = pd.read_csv(change_csv)
    required = {"participant_id", "days_from_baseline"}
    missing = required.difference(df.columns)
    if missing:
        raise ValueError(f"Missing columns in {change_csv}: {sorted(missing)}")

    last = _last_visit_rows(df)
    plot_cols = []
    rename = {}
    for metric in GLOBAL_FOLLOWUP_METRICS:
        col = f"{metric}_improvement_pct"
        if col in last.columns:
            plot_cols.append(col)
            rename[col] = label_metric(metric).replace("\n", " ")
    if not plot_cols:
        raise ValueError("No follow-up improvement percentage columns were found.")

    plot_df = last.set_index("participant_id")[plot_cols].apply(pd.to_numeric, errors="coerce")
    plot_df = plot_df.rename(columns=rename)
    plot_df = plot_df.replace([np.inf, -np.inf], np.nan)

    fig, ax = plt.subplots(figsize=(12.0, 6.2))
    plot_df.plot(kind="bar", ax=ax, width=0.86)
    ax.set_title("AE movement-matched follow-up: last visit vs baseline")
    ax.set_ylabel("Improvement (%)\npositive values indicate lower abnormality")
    ax.set_xlabel("Participant")
    ax.axhline(0, linewidth=1)
    ax.legend(title="Metric", loc="best")
    ax.tick_params(axis="x", rotation=0)

    finite_values = plot_df.to_numpy(dtype=float)
    finite_values = finite_values[np.isfinite(finite_values)]
    if finite_values.size:
        ymin = min(-10.0, float(np.nanmin(finite_values)) - 8.0)
        ymax = max(10.0, float(np.nanmax(finite_values)) + 8.0)
        ax.set_ylim(ymin, ymax)

    save_fig(fig, out_path, dpi)


def parse_common_movements(common_movements_csv: Optional[Path]) -> Dict[str, Set[str]]:
    if common_movements_csv is None or not common_movements_csv.exists():
        return {}
    df = pd.read_csv(common_movements_csv)
    if "participant_id" not in df.columns or "common_movements" not in df.columns:
        return {}
    out: Dict[str, Set[str]] = {}
    for _, row in df.iterrows():
        pid = str(row["participant_id"])
        movements = {m.strip() for m in str(row["common_movements"]).split(";") if m.strip()}
        out[pid] = movements
    return out


def compute_region_side_last_vs_baseline(
    region_side_csv: Path,
    common_movements_csv: Optional[Path],
    metric: str,
) -> pd.DataFrame:
    df = pd.read_csv(region_side_csv, low_memory=False)

    # Two formats are supported:
    #   1) sample-level region-side rows with a movement column;
    #   2) already movement-matched visit-level region-side rows without movement.
    base_required = {"participant_id", "acquisition_date", "region", "side", metric}
    missing = base_required.difference(df.columns)
    if missing:
        raise ValueError(f"Missing columns in {region_side_csv}: {sorted(missing)}")

    d = df.copy()
    d[metric] = numeric(d[metric])
    d = d.dropna(subset=["participant_id", "acquisition_date", "region", "side", metric])

    if "movement" in d.columns:
        d = d.dropna(subset=["movement"])
        common = parse_common_movements(common_movements_csv)
        if common:
            keep = []
            for _, row in d[["participant_id", "movement"]].iterrows():
                pid = str(row["participant_id"])
                mv = str(row["movement"])
                keep.append(mv in common.get(pid, set()))
            d = d[pd.Series(keep, index=d.index)].copy()

        # Step 1: sample/repetition rows -> participant-date-movement-region-side means.
        by_movement = (
            d.groupby(["participant_id", "acquisition_date", "movement", "region", "side"], as_index=False)[metric]
            .mean()
        )

        # Step 2: movement-first aggregation -> participant-date-region-side means.
        visit = (
            by_movement.groupby(["participant_id", "acquisition_date", "region", "side"], as_index=False)[metric]
            .mean()
        )
    else:
        # The file is already aggregated at visit-region-side level. This is the
        # format produced by some versions of eval_aev3_followup_matched.py.
        print(
            f"[INFO] {region_side_csv.name} has no 'movement' column; "
            "treating it as already movement-matched visit-level region-side data."
        )
        visit = (
            d.groupby(["participant_id", "acquisition_date", "region", "side"], as_index=False)[metric]
            .mean()
        )

    rows = []
    for pid, g in visit.groupby("participant_id"):
        dates = sorted(g["acquisition_date"].astype(str).unique().tolist())
        if len(dates) < 2:
            continue
        baseline_date = dates[0]
        last_date = dates[-1]
        baseline = g[g["acquisition_date"].astype(str) == baseline_date].set_index(["region", "side"])
        last = g[g["acquisition_date"].astype(str) == last_date].set_index(["region", "side"])
        idx = baseline.index.intersection(last.index)
        for region, side in idx:
            baseline_value = float(baseline.loc[(region, side), metric])
            last_value = float(last.loc[(region, side), metric])
            delta = last_value - baseline_value
            improvement = -delta  # lower abnormality is better
            rows.append(
                {
                    "participant_id": pid,
                    "baseline_date": baseline_date,
                    "last_date": last_date,
                    "region": region,
                    "side": side,
                    "region_side": f"{region} ({side})",
                    "baseline": baseline_value,
                    "last": last_value,
                    "delta": delta,
                    "improvement": improvement,
                }
            )
    return pd.DataFrame(rows)


def plot_followup_region_side(
    region_side_csv: Path,
    common_movements_csv: Optional[Path],
    out_path: Path,
    dpi: int,
    metric: str,
    top_n: int,
) -> None:
    changes = compute_region_side_last_vs_baseline(region_side_csv, common_movements_csv, metric)
    if changes.empty:
        raise ValueError("No region-side last-vs-baseline changes could be computed.")

    summary = (
        changes.groupby("region_side", as_index=False)
        .agg(
            mean_improvement=("improvement", "mean"),
            median_improvement=("improvement", "median"),
            n_participants=("participant_id", "nunique"),
        )
    )
    summary = summary[summary["n_participants"] >= 2].copy()
    summary["abs_mean_improvement"] = summary["mean_improvement"].abs()
    summary = summary.sort_values("abs_mean_improvement", ascending=False).head(top_n)
    summary = summary.sort_values("mean_improvement", ascending=True)

    fig_height = max(5.8, 0.38 * len(summary) + 1.8)
    fig, ax = plt.subplots(figsize=(10.5, fig_height))
    ax.barh(summary["region_side"], summary["mean_improvement"])
    ax.axvline(0, linewidth=1)
    ax.set_title(f"AE follow-up: largest regional changes in {label_metric(metric).replace(chr(10), ' ').lower()}")
    ax.set_xlabel("Mean improvement from baseline to last visit\npositive values indicate lower regional abnormality")
    ax.set_ylabel("Region / side")

    for y, v in enumerate(summary["mean_improvement"]):
        ha = "left" if v >= 0 else "right"
        offset = 0.01 if v >= 0 else -0.01
        ax.text(v + offset, y, f"{v:.2f}", va="center", ha=ha, fontsize=8)

    values = summary["mean_improvement"].to_numpy(dtype=float)
    if values.size:
        max_abs = float(np.nanmax(np.abs(values)))
        ax.set_xlim(-max_abs * 1.25, max_abs * 1.25)

    save_fig(fig, out_path, dpi)


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--reference_csv",
        default="reference_metric_comparison_global.csv",
        help="Path to reference_metric_comparison_global.csv.",
    )
    ap.add_argument(
        "--followup_change_csv",
        default="followup_change_from_baseline.csv",
        help="Path to movement-matched followup_change_from_baseline.csv.",
    )
    ap.add_argument(
        "--followup_region_side_csv",
        default="followup_region_side_metrics.csv",
        help="Path to movement-matched followup_region_side_metrics.csv.",
    )
    ap.add_argument(
        "--common_movements_csv",
        default="followup_common_movements_by_participant.csv",
        help="Path to followup_common_movements_by_participant.csv. Used to enforce movement-matched region-side aggregation.",
    )
    ap.add_argument("--out_dir", default="figures", help="Output directory for PNG figures.")
    ap.add_argument("--dpi", type=int, default=300)
    ap.add_argument("--top_n_regions", type=int, default=14)
    ap.add_argument(
        "--region_metric",
        default="hypokinesia_proxy",
        choices=["hypokinesia_proxy", "amplitude_log_ratio_abs", "trajectory_mae", "hyperkinesia_proxy", "counter_direction_ratio"],
        help="Metric used in the region-side follow-up figure. Default emphasizes regional hypokinesia.",
    )
    return ap.parse_args()


def main() -> None:
    args = parse_args()
    out_dir = Path(args.out_dir)
    ensure_dir(out_dir)

    reference_csv = Path(args.reference_csv)
    followup_change_csv = Path(args.followup_change_csv)
    followup_region_side_csv = Path(args.followup_region_side_csv)
    common_movements_csv = Path(args.common_movements_csv) if args.common_movements_csv else None

    plot_reference_comparison_auc(
        reference_csv=reference_csv,
        out_path=out_dir / "reference_comparison_auc_placeholder.png",
        dpi=args.dpi,
    )
    plot_followup_global_metrics(
        change_csv=followup_change_csv,
        out_path=out_dir / "aev3_followup_global_metrics_placeholder.png",
        dpi=args.dpi,
    )
    plot_followup_region_side(
        region_side_csv=followup_region_side_csv,
        common_movements_csv=common_movements_csv,
        out_path=out_dir / "aev3_followup_region_side_placeholder.png",
        dpi=args.dpi,
        metric=args.region_metric,
        top_n=args.top_n_regions,
    )

    print("[DONE] PNG figures generated.")


if __name__ == "__main__":
    main()
