#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
generate_regional_abnormality_heatmap.py

Generate a PNG heatmap for the FaceMoCap technical report:

  regional_abnormality_heatmap_placeholder.png

The figure summarizes AE-v3 region--side pathology contrast for selected
abnormality metrics. By default, each cell is the AUC obtained when separating
pathological samples from healthy evaluation samples, with the pathological
condition treated as the positive class and larger metric values interpreted as
larger abnormality.

Expected input:
  metrics_summary.csv generated by eval_healthy_reference_metrics.py

Typical usage:

python generate_regional_abnormality_heatmap.py \
  --metrics_summary align_mean_movement_refactor/healthy_reference_eval_metrics/metrics_summary.csv \
  --out_dir figures \
  --dpi 300

Output:
  figures/regional_abnormality_heatmap_placeholder.png
  figures/regional_abnormality_heatmap_values.csv
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Iterable, List, Tuple

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


DEFAULT_METRICS = [
    "trajectory_mae",
    "amplitude_log_ratio_abs",
    "hypokinesia_proxy",
    "hyperkinesia_proxy",
    "counter_direction_ratio",
]

METRIC_LABELS = {
    "trajectory_mae": "Trajectory\nabnormality",
    "amplitude_log_ratio_abs": "Amplitude\nabnormality",
    "hypokinesia_proxy": "Hypokinesia\nproxy",
    "hyperkinesia_proxy": "Hyperkinesia-like\nproxy",
    "counter_direction_ratio": "Counter-direction\nratio",
}


def safe_region_side(region: object, side: object) -> str:
    r = "" if pd.isna(region) else str(region).strip()
    s = "" if pd.isna(side) else str(side).strip()
    if not r and not s:
        return "unknown"
    if not s:
        return r
    return f"{r} ({s})"


def auc_pathological_greater(values: Iterable[float], labels: Iterable[int]) -> float:
    """AUC using average ranks. labels: 1 pathological, 0 healthy."""
    x = pd.Series(values, dtype="float64")
    y = pd.Series(labels, dtype="int64")
    ok = x.notna() & y.notna()
    x = x[ok]
    y = y[ok]
    n_pos = int((y == 1).sum())
    n_neg = int((y == 0).sum())
    if n_pos == 0 or n_neg == 0:
        return np.nan
    ranks = x.rank(method="average")
    sum_pos = float(ranks[y == 1].sum())
    auc = (sum_pos - n_pos * (n_pos + 1) / 2.0) / (n_pos * n_neg)
    return float(auc)


def compute_region_side_table(
    metrics_summary: Path,
    metrics: List[str],
    reference: str = "aev3",
    positive_condition: str = "pathological",
    negative_condition: str = "healthy",
) -> pd.DataFrame:
    needed = [
        "reference",
        "level",
        "condition",
        "group",
        "region",
        "side",
    ] + metrics

    df = pd.read_csv(metrics_summary, usecols=lambda c: c in set(needed), low_memory=False)
    missing = sorted(set(needed) - set(df.columns))
    if missing:
        raise ValueError(f"Missing columns in {metrics_summary}: {missing}")

    df["reference_norm"] = df["reference"].astype(str).str.strip().str.lower()
    df["condition_norm"] = df["condition"].astype(str).str.strip().str.lower()
    df["level_norm"] = df["level"].astype(str).str.strip().str.lower()

    d = df[
        (df["reference_norm"] == reference.lower())
        & (df["level_norm"] == "region_side")
        & (df["condition_norm"].isin([positive_condition.lower(), negative_condition.lower()]))
    ].copy()

    if d.empty:
        raise ValueError(
            "No rows found for reference='{}', level='region_side', conditions='{}'/'{}'.".format(
                reference, positive_condition, negative_condition
            )
        )

    d["region_side"] = [safe_region_side(r, s) for r, s in zip(d["region"], d["side"])]
    d["is_pathological"] = (d["condition_norm"] == positive_condition.lower()).astype(int)

    rows = []
    for region_side, g in d.groupby("region_side", dropna=False):
        row = {"region_side": region_side}
        for metric in metrics:
            vals = pd.to_numeric(g[metric], errors="coerce")
            labels = g["is_pathological"]
            healthy_vals = vals[labels == 0]
            path_vals = vals[labels == 1]
            row[f"{metric}_auc"] = auc_pathological_greater(vals, labels)
            row[f"{metric}_healthy_median"] = float(np.nanmedian(healthy_vals)) if healthy_vals.notna().any() else np.nan
            row[f"{metric}_pathological_median"] = float(np.nanmedian(path_vals)) if path_vals.notna().any() else np.nan
            row[f"{metric}_median_difference"] = row[f"{metric}_pathological_median"] - row[f"{metric}_healthy_median"]
            row[f"{metric}_n_healthy"] = int(healthy_vals.notna().sum())
            row[f"{metric}_n_pathological"] = int(path_vals.notna().sum())
        rows.append(row)

    out = pd.DataFrame(rows)
    out["mean_auc"] = out[[f"{m}_auc" for m in metrics]].mean(axis=1, skipna=True)
    out["max_auc"] = out[[f"{m}_auc" for m in metrics]].max(axis=1, skipna=True)
    out["mean_abs_median_difference"] = out[[f"{m}_median_difference" for m in metrics]].abs().mean(axis=1, skipna=True)
    return out.sort_values(["mean_auc", "max_auc"], ascending=False).reset_index(drop=True)


def select_region_sides(table: pd.DataFrame, metrics: List[str], top_n: int, selection: str) -> pd.DataFrame:
    if selection == "mean_auc":
        selected = table.sort_values(["mean_auc", "max_auc"], ascending=False).head(top_n)
    elif selection == "max_auc":
        selected = table.sort_values(["max_auc", "mean_auc"], ascending=False).head(top_n)
    elif selection == "median_difference":
        selected = table.sort_values("mean_abs_median_difference", ascending=False).head(top_n)
    else:
        raise ValueError(f"Unknown selection mode: {selection}")
    # Reverse so the highest-ranked region appears at the top of a horizontal heatmap.
    return selected.iloc[::-1].reset_index(drop=True)


def make_heatmap(
    table: pd.DataFrame,
    metrics: List[str],
    out_png: Path,
    value: str = "auc",
    title: str | None = None,
    dpi: int = 300,
) -> None:
    if value == "auc":
        mat = table[[f"{m}_auc" for m in metrics]].to_numpy(dtype=float)
        cbar_label = "AUC (pathological > healthy evaluation)"
        vmin, vmax = 0.5, 1.0
        cmap = "viridis"
        fmt = "{:.2f}"
        default_title = "AE-v3 region-side pathology contrast"
    elif value == "median_difference":
        mat = table[[f"{m}_median_difference" for m in metrics]].to_numpy(dtype=float)
        cbar_label = "Pathological median - healthy median"
        max_abs = float(np.nanmax(np.abs(mat))) if np.isfinite(mat).any() else 1.0
        vmin, vmax = -max_abs, max_abs
        cmap = "coolwarm"
        fmt = "{:.2f}"
        default_title = "AE-v3 region-side median abnormality difference"
    else:
        raise ValueError("value must be 'auc' or 'median_difference'")

    labels_y = table["region_side"].tolist()
    labels_x = [METRIC_LABELS.get(m, m.replace("_", "\n")) for m in metrics]

    height = max(6.0, 0.38 * len(labels_y) + 1.8)
    width = max(9.5, 1.55 * len(metrics) + 4.0)

    fig, ax = plt.subplots(figsize=(width, height))
    im = ax.imshow(mat, aspect="auto", cmap=cmap, vmin=vmin, vmax=vmax)

    ax.set_xticks(np.arange(len(metrics)))
    ax.set_xticklabels(labels_x, fontsize=9)
    ax.set_yticks(np.arange(len(labels_y)))
    ax.set_yticklabels(labels_y, fontsize=9)
    ax.set_xlabel("AE-v3 abnormality metric")
    ax.set_ylabel("Region / side")
    ax.set_title(title or default_title, pad=12)

    # Cell annotations. Use black/white threshold for readability.
    for i in range(mat.shape[0]):
        for j in range(mat.shape[1]):
            val = mat[i, j]
            if not np.isfinite(val):
                txt = "NA"
                color = "black"
            else:
                txt = fmt.format(val)
                if value == "auc":
                    color = "white" if val > 0.72 else "black"
                else:
                    color = "white" if abs(val) > 0.55 * max(abs(vmin), abs(vmax)) else "black"
            ax.text(j, i, txt, ha="center", va="center", fontsize=8, color=color)

    # Grid lines between cells.
    ax.set_xticks(np.arange(-0.5, len(metrics), 1), minor=True)
    ax.set_yticks(np.arange(-0.5, len(labels_y), 1), minor=True)
    ax.grid(which="minor", color="white", linestyle="-", linewidth=1.0)
    ax.tick_params(which="minor", bottom=False, left=False)

    cbar = fig.colorbar(im, ax=ax, fraction=0.035, pad=0.02)
    cbar.set_label(cbar_label)

    if value == "auc":
        ax.text(
            0.0,
            -0.085,
            "Values above 0.50 indicate larger abnormality values in pathological samples.",
            transform=ax.transAxes,
            ha="left",
            va="top",
            fontsize=9,
        )

    fig.tight_layout()
    out_png.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_png, dpi=dpi, bbox_inches="tight")
    plt.close(fig)


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--metrics_summary",
        default="align_mean_movement_refactor/healthy_reference_eval_metrics/metrics_summary.csv",
        help="Path to metrics_summary.csv generated by eval_healthy_reference_metrics.py.",
    )
    ap.add_argument("--out_dir", default="figures", help="Output directory for PNG and CSV files.")
    ap.add_argument("--out_name", default="regional_abnormality_heatmap_placeholder.png")
    ap.add_argument("--reference", default="aev3")
    ap.add_argument("--positive_condition", default="pathological")
    ap.add_argument("--negative_condition", default="healthy")
    ap.add_argument("--top_n", type=int, default=18, help="Number of region-side rows shown in the heatmap.")
    ap.add_argument(
        "--selection",
        choices=["mean_auc", "max_auc", "median_difference"],
        default="mean_auc",
        help="Criterion used to select region-side rows.",
    )
    ap.add_argument(
        "--value",
        choices=["auc", "median_difference"],
        default="auc",
        help="Cell values shown in the heatmap.",
    )
    ap.add_argument("--dpi", type=int, default=300)
    ap.add_argument("--metrics", nargs="*", default=DEFAULT_METRICS)
    return ap.parse_args()


def main() -> None:
    args = parse_args()
    metrics_summary = Path(args.metrics_summary)
    out_dir = Path(args.out_dir)
    out_png = out_dir / args.out_name

    table = compute_region_side_table(
        metrics_summary=metrics_summary,
        metrics=args.metrics,
        reference=args.reference,
        positive_condition=args.positive_condition,
        negative_condition=args.negative_condition,
    )

    out_dir.mkdir(parents=True, exist_ok=True)
    table.to_csv(out_dir / "regional_abnormality_heatmap_values_all_region_sides.csv", index=False)

    selected = select_region_sides(table, args.metrics, top_n=args.top_n, selection=args.selection)
    selected.to_csv(out_dir / "regional_abnormality_heatmap_values.csv", index=False)

    title = (
        "AE-v3 region-side pathology contrast"
        if args.value == "auc"
        else "AE-v3 region-side pathological median difference"
    )
    make_heatmap(
        table=selected,
        metrics=args.metrics,
        out_png=out_png,
        value=args.value,
        title=title,
        dpi=args.dpi,
    )
    print(f"[OK] Wrote {out_png}")
    print(f"[OK] Wrote {out_dir / 'regional_abnormality_heatmap_values.csv'}")
    print(f"[OK] Wrote {out_dir / 'regional_abnormality_heatmap_values_all_region_sides.csv'}")


if __name__ == "__main__":
    main()
